### ISSUE TITLE
Write CDATA node with a redundant "]]"

### ISSUE THREAD

**Issue by slzhu** [michaelrsweet/mxml#216]
In the source code(mxml-file.c),  It says

> CDATA element do not use character entities, but also need the "]]" terminator added at the end.

But I still don't understand the reason for the "]]" terminator.
I have do a test:
1、new a CDATA node by 'mxmlNewCDATA', the data is "test for cdata"
2、read the node by 'mxmlGetCDATA' immediately
3、save the whole tree to a xml file

The result is:
->2、the string read out is more than a ']]', it is "test for cdata]]"
->3、in the xml file, the CDATA has a redundant "]]", it is 

`<![CDATA[test for cdata]]]]>`

But as I known, it should be

`<![CDATA[test for cdata]]>`

Is this a bug or for other purpose ? @michaelrsweet

**Comment by michaelrsweet** [comment]
mxmlNewCDATA adds the "<![CDATA[...]]" wrapper around the string for you. When you call mxmlGetCDATA the returned string includes the trailing "]]" (since it was added for you).

I will add a note about this to the documentation, but short of making a copy of the string there isn't any way around this in Mini-XML 2.x. In 3.x I plan on making CDATA nodes have their own type so we can just store the raw string.

**Comment by michaelrsweet** [comment]
Actually, looking at the load code we strip the trailing "]]", so mxmlNewCDATA should do the same.

**Comment by michaelrsweet** [comment]
Fixed:

[master e0db328] Don't add ]] to the CDATA node (Issue #216)
