### ISSUE TITLE
Use of library under plain Apache License without NOTICE exceptions

### ISSUE THREAD

**Issue by stevedlawrence** [michaelrsweet/mxml#270]
We are considering using mxml in some future additions to the [Apache Daffodil](https://github.com/apache/incubator-daffodil) project. But there are concerns that the exceptions mentioned in the NOTICE file are not compatible with the Apache license and so can't be used in the project. See the Apache discussion here: https://issues.apache.org/jira/browse/LEGAL-527

Would it be possible to allow use of the mxml library under the plain Apache license without the mentioned exceptions?

**Comment by michaelrsweet** [comment]
@stevedlawrence FWIW, I blatantly stole this exception from Clang and CUPS, both of which have adopted this [Fizbin language](https://www.youtube.com/watch?v=v77SF4TFUoM) in order to work around the nightmare that is the GNU GPL. I mean really, who makes two licenses that are totally incompatible with each other?

If you are embedding Mini-XML in the project, I have no problems with you removing the exception language from your copy of the NOTICES file, although I would expect you to keep my copyright notice. If you are just linking against Mini-XML, the exception doesn't even apply - it only applies when you try to combine Mini-XML with something that is GPL2-only or LGPL2-only, and then only if a court of law challenges it. It was approved by Apple legal for CUPS back when I still worked for Apple, and by the Clang project, so I have to assume all those lawyers were happy with the final wording... 🤷‍♂️ IANAL, etc. etc.

**Comment by stevedlawrence** [comment]
@michaelrsweet Sounds good. Thanks for the clarification.

**Comment by stevedlawrence** [comment]
Based on feedback from ASF, would it be possible to add a blurb in the README explaining that the license is available under either a pure ALv2 license or ALv2 + exception?

**Comment by michaelrsweet** [comment]
[master f245429] I am beginning to dislike lawyers. (Issue #270)

**Comment by jochenw** [comment]
> [master [f245429](https://github.com/michaelrsweet/mxml/commit/f2454294f335e069390faf9ae2e9e602d2348377)] I am beginning to dislike lawyers. (Issue #270)


Steve: We aren't asking, because we love lawyers. :-)
