### ISSUE TITLE
mxmlOptionsSetTypeValue(opt, MXML_TYPE_TEXT) can not load node text...

### ISSUE THREAD

**Issue by zlifes** [michaelrsweet/mxml#315]
test xml node like: <text1>test  text4</text1>.

mxmlOptionsSetTypeValue(opt, MXML_TYPE_TEXT)  and load xml, the node text1's text is "test", not "test  text4".

but Mini-XML v4.0b1 is OK.

**Comment by michaelrsweet** [comment]
Can you provide a complete example file and source code demonstrating the issue you are seeing?

**Comment by zlifes** [comment]
example file string:
const char *str = "<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>"
"<Workspace title="Workspace1" ver="1.0">"
"    <node1>testtext2</node1>"
"   <node2>test text3</node2>"
"</Workspace>";

source code demonstrating:
mxml_node_t *doc;
mxml_options_t *lvar_xmlopt=mxmlOptionsNew();
mxmlOptionsSetTypeValue(lvar_xmlopt, MXML_TYPE_TEXT);
doc=mxmlLoadString(NULL,lvar_xmlopt,str);

the node2's text is "test", not "test text3". but Mini-XML v4.0b1 is OK.

try mxmlOptionsSetTypeValue(lvar_xmlopt, MXML_TYPE_OPAQUE), OK, the node2's text is "test text3".

**Comment by zlifes** [comment]
`example file string:
const char *str = "<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>"
"<Workspace title="Workspace1" ver="1.0">"
"    <node1>testtext2</node1>"
"   <node2>test text3</node2>"
"</Workspace>";

source code demonstrating:
mxml_node_t *doc;
mxml_options_t *lvar_xmlopt=mxmlOptionsNew();
mxmlOptionsSetTypeValue(lvar_xmlopt, MXML_TYPE_TEXT);
doc=mxmlLoadString(NULL,lvar_xmlopt,str);

the node2's text is "test", not "test text3". but Mini-XML v4.0b1 is OK.

try mxmlOptionsSetTypeValue(lvar_xmlopt, MXML_TYPE_OPAQUE), OK, the node2's text is "test text3". `

**Comment by zlifes** [comment]
Example files can be found in the attachment test1.xml

source code demonstrating:
mxml_node_t *doc;
mxml_options_t *lvar_xmlopt=mxmlOptionsNew();
mxmlOptionsSetTypeValue(lvar_xmlopt, MXML_TYPE_TEXT);
doc=mxmlLoadFilename(NULL,lvar_xmlopt,"test1.xml");

the node2's text is "test", not "test text3". but Mini-XML v4.0b1 is OK.

try mxmlOptionsSetTypeValue(lvar_xmlopt, MXML_TYPE_OPAQUE), OK, the node2's text is "test text3".

**Comment by michaelrsweet** [comment]
@zlifes This is the most common error made by developers, which is why I talk about it in several places in the Mini-XML programming manual included with the software...

`MXML_TYPE_TEXT` nodes are whitespace-delimited text fragments ("words"). Each text node has a string value and a boolean whitespace indicator, so for your example there will be *2* value nodes, one for each word.

`MXML_TYPE_OPAQUE` nodes are literal text strings containing all of the characters between the begin and end tags.

There are times for using both of these types, but in this case it sounds like you want to use `MXML_TYPE_OPAQUE`.
